spring:
    datasource:
        name: dzj
        url: jdbc:mysql://192.168.0.134:3306/erp?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true
        username: dzj-app
        password: dzjapp
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 100
        initialSize: 1
        maxWait: 60000
        spring.datasorce.minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
        ###########页面配置前缀
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        ###########后缀
        suffix: .jsp
    #####配置序列化时,不返回null值到前端
#    jackson:
#      default-property-inclusion: ALWAYS


#mybatis:
 # mapper-locations: com.dzj.exx.mapper.*/*.xml  #\u6CE8\u610F\uFF1A\u4E00\u5B9A\u8981\u5BF9\u5E94mapper\u6620\u5C04xml\u6587\u4EF6\u7684\u6240\u5728\u8DEF\u5F84
  #type-aliases-package: com.dzj.exx.model  # \u6CE8\u610F\uFF1A\u5BF9\u5E94\u5B9E\u4F53\u7C7B\u7684\u8DEF\u5F84
#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
