spring:
    datasource:
        name: dzj
        url: jdbc:mysql://rm-wz9p73l18gj48fn3zo.mysql.rds.aliyuncs.com:3306/test-erp?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true
        username: dzj_user
        password: dzj88_exx
        #url: jdbc:mysql://192.168.5.131:3306/erp?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true
        #username: dzjerp
        #password: dzj_EXX88
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 100
        initialSize: 1
        maxWait: 60000
        spring.datasorce.minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
    aop:
      #auto: true
      proxy-target-class: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/exx/dzj/mapper/**/*Mapper.xml
  table-prefix: tab_

# 阿里云存储配置
aliyun:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI24Fekt4cpDoy
  accessKeySecret: iw4Yp42IqB5wh461RITJJexpCaFhJw
  bucketName: exx-erp
  subdir: producet-images
  active: test
